### ISSUE TITLE
the workflow did not run through.

### ISSUE THREAD

**Issue by wk1025** [uyab/laravolt-sandbox-5#1]
Can you share the dynamic-approval.bpmn file? After the deployment, the workflow did not run through.

**Comment by uyab** [comment]
[dynamic-approval.bpmn.zip](https://github.com/uyab/laravolt-sandbox-5/files/6955304/dynamic-approval.bpmn.zip)

**Comment by wk1025** [comment]
Thank you for your contribution

**Comment by uyab** [comment]
Anyway, do you currentlly use Camunda BPMN to develop workflow application?

**Comment by wk1025** [comment]
Yes, workflow applications are being developed using camunda BPMN.
